import Vue from 'vue';
import Container from './common/container';
import Header from './common/header';
import topBar from './common/top_bar';
import Breadcrumb from './common/breadcrumb';
import Aside from './common/aside';
import Timeline from './common/timeline';
import TimelineItem from './common/timeline_item';
import ChartContainer from './common/charts/chart_container';
import Pie from './common/charts/pie';
import Column from './common/charts/column';
import Panel from './common/panel';
import CardPanel from './common/cardPanel';
import FilterPageList from './common/filterPageList';
import ImportFileDialog from './common/importFileDialog';
import ViewContentDialog from './common/viewContentDialog';
import AbnormalJobs from './common/abnormalJobs';
import TimeoutJobs from './common/timeoutJobs';
import UnableFailoverJobs from './common/unableFailoverJobs';
import AbnormalContainers from './common/abnormalContainers';
import CronPredictDialog from './common/cronPredictDialog';
import InputTags from './common/inputTags';
import BatchMigrateDialog from './common/dialog/batch_migrate_dialog';
import MigrateStatusDialog from './common/dialog/migrate_status_dialog';
import AddConfigDialog from './common/dialog/add_config_dialog';

Vue.component('Container', Container);
Vue.component('Header', Header);
Vue.component('Top-bar', topBar);
Vue.component('Breadcrumb', Breadcrumb);
Vue.component('Aside', Aside);
Vue.component('Timeline', Timeline);
Vue.component('Timeline-item', TimelineItem);
Vue.component('Chart-container', ChartContainer);
Vue.component('Pie', Pie);
Vue.component('Column', Column);
Vue.component('Panel', Panel);
Vue.component('CardPanel', CardPanel);
Vue.component('FilterPageList', FilterPageList);
Vue.component('ImportFileDialog', ImportFileDialog);
Vue.component('ViewContentDialog', ViewContentDialog);
Vue.component('AbnormalJobs', AbnormalJobs);
Vue.component('TimeoutJobs', TimeoutJobs);
Vue.component('UnableFailoverJobs', UnableFailoverJobs);
Vue.component('AbnormalContainers', AbnormalContainers);
Vue.component('CronPredictDialog', CronPredictDialog);
Vue.component('InputTags', InputTags);
Vue.component('batch-migrate-dialog', BatchMigrateDialog);
Vue.component('migrate-status-dialog', MigrateStatusDialog);
Vue.component('add-config-dialog', AddConfigDialog);
